name: "Validate Dart Code"
description: "Validates Dart code by running tests, linter, and build runner"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
    - name: Install dependencies
      shell: bash
      run: flutter pub get
    - name: Run build runner
      shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - name: Run tests
      shell: bash
      run: flutter test
    - name: Run linter
      shell: bash
      run: flutter analyze
    - name: Run tests
      shell: bash
      run: flutter test --coverage
    - name: Report test results
      uses: dorny/test-reporter@v2
      with:
        name: Flutter Tests
        path: reports/test-results.json
        reporter: flutter-json
