name: "Release Main"
on:
  push:
    branches:
      - main

jobs:
  # Validate the Dart code
  validate_dart:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Dart code
        uses: ./.github/actions/validate-dart

  version:
    needs: validate_dart
    uses: ./.github/workflows/publish_workflow.yaml
    secrets:
      app_private_key: ${{ secrets.BUMPER_APP_KEY }}
    with:
      app_id: ${{ vars.BUMPER_APP_ID }}
      git_push_branch: main
      git_push: true
      use_local_version: true
